---
title: Paulo Tijero
description: Fullstack Software Engineer, Technical Writer, and Funny Speaker
domain: https://paulotijero.dev
language: en
repository: https://github.com/paulotijero/personal-site/
email: paulotijero@gmail.com
social:
  twitter: paulotijero
  github: paulotijero
  linkedin: paulotijero
  meetup: 273278704
icon: /static/tijerotexeira.png
navigation:
  - name: Bio
    path: /about/
incremental: false
analytics: UA-138758078-1
