---
title: Paulo Tijero
description: Software Engineer, Fullstack Developer, Technical Writter, and Funny Speaker
domain: https://paulotijero.dev
language: en
repository: https://github.com/paulotijero/personal-site/
email: paulotijero@gmail.com
social:
  twitter: paulotijero
  github: paulotijero
  linkedin: paulotijero
  meetup: 273278704
icon: /static/tijerotexeira.png
navigation:
  - name: Papers
    path: /papers/
  - name: About me
    path: /about/
incremental: false
analytics: UA-138758078-1
