---
title: Paulo Tijero
description: Full Stack Developer
domain: https://paulotijero.dev
language: en
repository: https://github.com/paulotijero/personal-site/
email: paulotijero@gmail.com
social:
  twitter: paulotijero
  github: paulotijero
  linkedin: paulotijerotexeira
  meetup: 273278704
icon: /static/tijerotexeira.png
navigation:
  - name: About me
    path: /about/
incremental: false
analytics: UA-138758078-1
